version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_kero
    environment:
      POSTGRES_USER: #usuario
      POSTGRES_PASSWORD: #senha
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_kero
    environment:
      PGADMIN_DEFAULT_EMAIL: #email
      PGADMIN_DEFAULT_PASSWORD: #senha
    ports:
      - "8081:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
