spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kero
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  flyway:
    enabled: true
    baseline-on-migrate: true 
    locations: classpath:db/migration   
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 64e529da20f707
    password: 008b9815173691
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
